#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products

/products:
  get:
    description: To get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID": "73657467",
                "productName": "Yonatan Mule Course",
                "productProvider": "Udemy",
                "productDescription": "Complete mule developer course"
              }
      